services: # add services per entity, e.g. once for identity-owner, issuer, etc.
  identity-issuer:
    build: ./identity-issuer
    ports:
      - "3333:3000" # mapping the external port 3333 to container's internal port 3000
    command: node TEST.js
  service-provider:
    build: ./service-provider
    ports:
      - "3334:3000" # mapping the external port 3333 to container's internal port 3000
    command: node TEST.js

  vdr:
    build: ./vdr
    ports:
      - "3334:3000" # mapping the external port 3333 to container's internal port 3000
    command: pnpm dev
