version: '3.8'
services:
  web:
    build: ./backend
    ports:
      - "3333:3000"
    command: pnpm run start
    environment:
      - SERVER_PORT=3333
    extra_hosts:
      - "host.docker.internal:host-gateway"