services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  identity-issuer:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:admin@db:5432/postgres
    ports:
      - "3334:3000"
    depends_on:
      - db
    entrypoint: ["./entrypoint.sh"]
    command: ["pnpm", "run", "dev"]

volumes:
  pgdata: